create table Bank (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table Branch (
    id bigint generated by default as identity,
    branch_details varchar(255),
    bank_id bigint,
    primary key (id),
    foreign key (bank_id) references Bank(id) on delete cascade
);

create table Customer (
    id bigint generated by default as identity,
    name varchar(100),
    branch_id bigint,
    contact_details varchar(255),
    email varchar(255),
    primary key (id),
    foreign key (branch_id) references Branch(id) on delete cascade
);

create table Account (
    id bigint generated by default as identity,
    branch_id bigint,
    account_number varchar(20),
    account_owner_id bigint,
    account_status bit,
    account_type varchar(30),
    current_balance double,
    primary key (id),
    foreign key (account_owner_id) references Customer(id) on delete cascade,
    constraint index_branch_id INDEX (branch_id),
    constraint unique_account_branch UNIQUE (branch_id, account_number)
);

create table Transaction (
   id bigint generated by default as identity,
   account_from_id bigint,
   account_to_id bigint NOT NULL,
   transaction_amount double,
   transaction_date_time timestamp,
   transaction_type varchar(30),
   primary key (id),
   foreign key (account_from_id) references Account(id) on delete cascade,
   foreign key (account_to_id) references Account(id) on delete cascade,
);
